version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/local/bin/
      - wget -q -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
      - chmod +x /usr/local/bin/terragrunt
      - terraform -v
      - terragrunt -v
  pre_build:
    commands:
      # CodeBuild environment variables
      #   BRANCH_NAME -- GitHub branch that triggered the CodeBuild project
      - |
        if [[ -z "${BRANCH_NAME}" ]]; then
          # extract branch from github webhook
          BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3)
        fi
      - "echo Triggered Branch: $BRANCH_NAME"
      - IFS=" && " read -a COMMANDS <<< $COMMANDS
      - "echo Target Directory: $TARGET_DIR"
      - "echo Commands: ${COMMANDS[@]}"
  build:
    commands:
      - |
        if [ -d "$TARGET_DIR" ]; then
          cd $TARGET_DIR
          for command in "${COMMANDS[@]}"; do
            echo ""
            echo "*************** Executing Command: ${command} ******************"
            echo "******* At directory: ${$TARGET_DIR} ********"
            echo "*************************************************"
            $command || exit 1
          done
        else
          echo ""
          echo "*************** Skipping Directory: ${TARGET_DIR} ******************"
          echo "******* ${TARGET_DIR} is not a valid directory in the source repo: ${CODEBUILD_SRC_DIR} ********"
          echo "*************************************************"
          exit 1
        fi