# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "private_bucket_name" {}
variable "tf_state_bucket_name" {}
variable "region" {}
variable "env" {}
variable "tags" {
  type = map(string)
}
variable "github_repo_url" {}
