# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key    = "usr-olap/deployment/dev/networking/tf-state/terraform.tfstate"
    region = "us-west-2"
    bucket = "private-sparkify"
  }
}
