version: 0.2

phases:
  install:
    commands:
      # - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      # - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      # - rm terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      # - mv terraform /usr/local/bin/
      # - docker pull hashicorp/terraform
      
  build:
    commands:
      - |
        : '
        CodeBuild environment variables:
          BRANCH_NAME -- GitHub branch that triggered the CodeBuild project
          TF_ROOT_DIR -- Directory within branch ($BRANCH_NAME) that will be iterated through for terraform planning and testing
        '
        # if BRANCH_NAME is not defined in codebuild 
        if [[ -z "${BRANCH_NAME}" ]]; then
          # extract branch from github webhook
          BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3)
        fi
        # if TF_ROOT_DIR is not defined in codebuild 
        if [[ -z "${TF_ROOT_DIR}" ]]; then
          if [ $BRANCH_NAME = "master" ]; then
            # Iterate through both dev and prod directories
            TF_ROOT_DIR=${TF_ROOT_DIR}/*/
          else
            # Iterate only through BRANCH_NAME directory
            TF_ROOT_DIR=${TF_ROOT_DIR}/${BRANCH_NAME}/
          fi
        fi
      - |
        for dir in $TF_ROOT_DIR; do
          #get list of non-hidden directories within $dir/
          service_dir_list=$(find "${dir}" -type d | grep -v '/\.')
          for sub_dir in $service_dir_list; do
            #if $sub_dir contains .tf or .tfvars files
            if (ls ${sub_dir}/*.tf) > /dev/null 2>&1 || (ls ${sub_dir}/*.tfvars) > /dev/null 2>&1; then
              cd $sub_dir 
              echo ""
              echo "*************** terraform init ******************"
              echo "******* At directory: ${sub_dir} ********"
              echo "*************************************************"
              docker run -i -t hashicorp/terraform:$TERRAFORM_VERSION init || terraform init
              echo ""
              echo "*************** terraform plan ******************"
              echo "******* At directory: ${sub_dir} ********"
              echo "*************************************************"
              docker run -i -t hashicorp/terraform:$TERRAFORM_VERSION plan || terraform plan
              cd - > /dev/null 
            fi
          done 
        done
      

