version: 0.2

phases:
    pre_build:
      commands:
        - echo Logging into Amazon ECR...
        - aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION
    build:
      commands:
        - export IMAGE_TAG=${TAG_PREFIX}-${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - cd $BUILD_PATH
        - bash $BUILD_SH
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $ECR_REPO_URL:$IMAGE_TAG