# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key    = "usr-olap/deployment/dev/data_pipelines/tf/airflow/tf-state/terraform.tfstate"
    region = "us-west-2"
    bucket = "private-sparkify"
  }
}
