# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "resource_prefix" {}
variable "client" {}
variable "project_id" {}
variable "private_bucket_name" {}
variable "private_bucket_arn" {}
variable "tf_state_bucket_name" {}
variable "tf_state_bucket_arn" {}
variable "region" {}
variable "env" {}
variable "tags" {
  type = map(string)
}
