# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  version = "~> 3.2.0"
  region  = var.region
  profile = var.aws_profile
}

data "aws_region" "current" {}

data "aws_caller_identity" "current" {}
