# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "env" {
  default = null
}

variable "region" {
  default = null
}

variable "aws_profile" {
  default = null
}

variable "admin_role_name" {
  default = null
}

variable "admin_role_tags" {
  type = map(string)
  default = {}
}

variable "poweruser_role_name" {
  default = null
}

variable "poweruser_role_tags" {
  type = map(string)
  default = {}
}

variable "readonly_role_name" {
  default = null
}

variable "readonly_role_tags" {
  type = map(string)
  default = {}
}

