version: 0.2
batch:
  build-graph:
    - identifier: networking
      env:
        compute-type: BUILD_GENERAL1_SMALL 
        variables:
          TF_DIR_PATH_TMPL: "deployment/networking/$BRANCH_NAME"
    - identifier: data_pipeline
      env:
        compute-type: BUILD_GENERAL1_SMALL
        variables:
          TF_ROOT_DIR_TMPL: "deployment/data_pipeline/$BRANCH_NAME"
          TF_SUB_DIRS: "dags/sparkify_etl, dags/sparkify_analytics"
            
      depend-on:
        - networking
env:
  shell: bash
  variables:
    TERRAFORM_VERSION: 0.12.28
    TERRAGRUNT_VERSION: 0.25.4
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -q
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -q
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/local/bin/
      - unzip terraform_${TERRAGRUNT_VERSION}_amd64.zip && mv terragrunt /usr/local/bin/
  pre_build:
    commands:
      # CodeBuild environment variables
      #   BRANCH_NAME -- GitHub branch that triggered the CodeBuild project
      #   TG_ROOT_DIR -- Root deployment directory
      #   LIVE_BRANCHES -- Branches that represent a live cloud environment
      - |
        if [[ -z "${BRANCH_NAME}" ]]; then
          # extract branch from github webhook
          BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3)
        fi
      - "echo Triggered Branch: $BRANCH_NAME"
      - |
        if [[ " ${LIVE_BRANCHES[*]} " == *"$BRANCH_NAME"* ]]; then
          TG_WORKING_DIRS=$TG_ROOT_DIR/$BRANCH_NAME
        else
          #iterate through all live branch directories
          TG_WORKING_DIRS=$TG_ROOT_DIR/*
        fi
      - "echo Terragrunt plan-all target directories: $TG_WORKING_DIRS"
  build:
    commands:
      - |
        for dir in $TG_WORKING_DIRS; do
          cd $dir
          terragrunt plan-all 
          cd - > /dev/null 