version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/local/bin/
      - wget -q -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
      - chmod +x /usr/local/bin/terragrunt
      - terraform -v
      - terragrunt -v
  pre_build:
    commands:
      # CodeBuild environment variables
      #   BRANCH_NAME -- GitHub branch that triggered the CodeBuild project
      #   TG_ROOT_DIR -- Root deployment directory
      #   LIVE_BRANCHES -- Branches that represent a live cloud environment
      - |
        if [[ -z "${BRANCH_NAME}" ]]; then
          # extract branch from github webhook
          BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3)
        fi
      - "echo Triggered Branch: $BRANCH_NAME"
      - |
        if [[ " ${LIVE_BRANCHES[*]} " == *"$BRANCH_NAME"* ]]; then
          TG_WORKING_DIRS=$TG_ROOT_DIR/$BRANCH_NAME
        else
          #iterate through all live branch directories
          TG_WORKING_DIRS=$TG_ROOT_DIR/*/
        fi
      - "echo Terragrunt plan-all target directories: $TG_WORKING_DIRS"
  build:
    commands:
      - |
        for dir in $TG_WORKING_DIRS; do
          cd $dir
          echo ""
          echo "*************** terragrunt plan-all ******************"
          echo "******* At directory: ${dir} ********"
          echo "*************************************************"
          terragrunt apply-all || exit 1
          cd - > /dev/null 
        done