version: 0.2

phases:
    pre_build:
      commands:
        - aws ssm put-parameter \
          --name ${DEPLOYMENT_GROUP_NAME}-IMAGE-TAG \
          --value $CODEBUILD_RESOLVED_SOURCE_VERSION \
          --description "Airflow image tag used for specified deployment group"
          --type "String" \
          --tier Standard \
          --overwrite
    build:
      commands:
        - echo Pusing Airflow src to S3 on `date`
        - S3_LOCATION=$(echo s3://$BUCKET/$KEY/$CODEBUILD_RESOLVED_SOURCE_VERSION.zip)
        - $(aws deploy push \
            --application-name $APPLICATION_NAME \
            --description "Push bundled Airflow src to S3 on `date` from Github commit id - $CODEBUILD_RESOLVED_SOURCE_VERSION" \
            --s3-location $S3_LOCATION \
            --source $SOURCE) \
            --ignore-hidden-files 
    post_build:
      commands:
        - echo Deploying Airflow src to $DEPLOYMENT_GROUP_NAME on `date`
        - $(aws deploy create-deployment \
            --application-name $APPLICATION_NAME \
            --deployment-config-name $DEPLOYMENT_CONFIG_NAME \
            --deployment-group-name $DEPLOYMENT_GROUP_NAME \
            --description "Deployed Airflow src on `date` from Github commit id - $CODEBUILD_RESOLVED_SOURCE_VERSION" \
            --s3-location bucket=$BUCKET, \
                bundleType=zip, \
                key=$KEY/$CODEBUILD_RESOLVED_SOURCE_VERSION.zip)