# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region = "us-west-2"
    bucket = "private-sparkify"
    key    = "usr-olap/deployment/dev/data_pipelines/tf/dags/sparkify_analytics/tf-state/terraform.tfstate"
  }
}
