- name: 1-source
  actions:
    - name: ${branch_name}-source
      category: Source
      owner: AWS
      provider: CodeStarSourceConnection
      version: 1
      output_artifacts:
        - ${branch_name}
      configuration:
        ConnectionArn: ${codestar_conn_arn}
        FullRepositoryId: ${repo_id}
        BranchName: ${branch_name}

- name: 2-entrypoint
  actions:
    - name: tf-validate
      category: Test
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - entrypoint-tf-testing-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/entrypoint-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${validate_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 1

    - name: tf-plan
      category: Test
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - entrypoint-tf-plan-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/entrypoint-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${plan_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 2

    - name: tf-manual-approval
      category: Approval
      owner: AWS
      provider: Manual
      version: 1
      run_order: 3

    - name: tf-apply
      category: Build
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - entrypoint-tf-apply-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/entrypoint-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${apply_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 4

- name: 3-shared-services
  actions:
    - name: tf-validate
      category: Test
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - shared-services-tf-testing-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/shared-services-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${validate_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 1

    - name: tf-plan
      category: Test
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - shared-services-tf-plan-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/shared-services-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${plan_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 2

    - name: tf-manual-approval
      category: Approval
      owner: AWS
      provider: Manual
      version: 1
      run_order: 3

    - name: tf-apply
      category: Build
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - shared-services-tf-apply-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/shared-services-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${apply_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 4
          
- name: 4-env-accounts
  actions:
    - name: dev-tf-validate
      category: Test
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - dev-tf-testing-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/dev-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${validate_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 1

    - name: dev-tf-plan
      category: Test
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - dev-tf-plan-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/dev-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${plan_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 2

    - name: dev-tf-manual-approval
      category: Approval
      owner: AWS
      provider: Manual
      version: 1
      run_order: 3

    - name: dev-tf-apply
      category: Build
      owner: AWS
      provider: CodeBuild
      role_arn: ${tf_build_role_arn}
      version: 1
      input_artifacts: 
        - ${branch_name}
      output_artifacts:
        - dev-tf-apply-output
      configuration:
        ProjectName: ${tf_build_name}
        EnvironmentVariables: >-
          [ 
            {
              "name": "TARGET_DIR",
              "value": "${infrastructure_dir}/dev-account/",
              "type": "PLAINTEXT"
            },
            {
              "name": "COMMANDS",
              "value": "${apply_command}",
              "type": "PLAINTEXT"
            }
          ]
      run_order: 4
        
