# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key     = "usr-olap/CI_CD/tf-state/terraform.tfstate"
    region  = "us-west-2"
    bucket  = "private-sparkify"
    encrypt = true
  }
}
