default_args: &dag_default_args
    owner: sparkify
    environment: dev   
    aws_conn_id: aws_credentials
    region: us-west-2 
    retries: 0
    retry_delay: 5
    email_on_retry: False
    depends_on_past: False
    catchup: False
dags:
    sparkify_analytics:
        dag_id: sparkify_analytics-v0.0.1
        description: Transforms raw data to parquet data and executes AWS Athena queries
        # schedule_interval: None
        # start_date: \2018-11-11
        # end_date: \2018-11-11
        max_active_runs: 1
        
        


